<a href="https://colab.research.google.com/github/Sakkkkkkkkkk/Sakkkkkkkkkk1/blob/main/DSML_Assignment_2(fb_csv).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

df = pd.read_csv('/content/fb.csv')

In [93]:
# 1) Count how many number of posts are paid and unpaid
paid = df['Paid'].value_counts()[1]
unpaid = df['Paid'].value_counts()[0]
print("Paid:", paid)
print("Unpaid:",unpaid)

Paid: 139
Unpaid: 360

In [41]:
# 2) Display only Page type, Month, likes, comments and shares
x = df[['Type', 'Post Month', 'like', 'comment', 'share']]
x

       Type  Post Month    like  comment  share
0     Photo          12    79.0        4   17.0
1    Status          12   130.0        5   29.0
2     Photo          12    66.0        0   14.0
3     Photo          12  1572.0       58  147.0
4     Photo          12   325.0       19   49.0
..      ...         ...     ...      ...    ...
495   Photo           1    53.0        5   26.0
496   Photo           1    53.0        0   22.0
497   Photo           1    93.0        4   18.0
498   Photo           1    91.0        7   38.0
499   Photo           1    91.0        0   28.0

[500 rows x 5 columns]

In [44]:
# 3) Find average number of likes to the post in September month
x=df[df['Post Month'] == 9]['like'].mean()
x

230.94444444444446

In [45]:
# 4) Print the information about the posts which are links
df[df['Type'] == 'Link']

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32
49,138353,Link,1,12,2,2,0.0,1536,3094,84,76,99,2903,1407,76,1,12.0,1.0,14
86,137177,Link,1,11,4,3,0.0,21176,54779,330,228,329,13858,5248,185,2,130.0,31.0,163
136,136393,Link,1,10,5,10,0.0,4664,9463,204,182,251,7196,3324,173,0,32.0,16.0,48
140,136013,Link,1,10,4,3,0.0,68992,229733,1032,975,1345,17842,8032,635,15,143.0,44.0,202
149,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
344,117764,Link,1,5,1,2,0.0,12540,19301,344,322,396,16914,11008,289,3,46.0,14.0,63
372,113028,Link,1,4,5,7,1.0,35360,45260,339,325,477,9105,5472,156,7,38.0,11.0,56
403,107907,Link,1,4,2,6,0.0,70912,94172,1374,1106,1267,42338,27232,788,1,379.0,40.0,420
408,106928,Link,1,4,6,4,0.0,34192,42092,338,322,389,22907,16464,230,1,36.0,7.0,44
425,102112,Link,3,3,1,3,0.0,6876,10885,282,245,337,9403,5752,259,2,68.0,15.0,85
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137

In [49]:
# 5) How many total shares are present for the video posts
x=df[df['Type']=='Video']['share'].sum()
x

365.0

In [55]:
# 6) In which hour of the day maximum posts are posted
df['Post Hour'].value_counts().idxmax()

3

In [69]:
# 7) In which day of October, maximum number of interactions are found
x = df[df['Post Month'] == 10].groupby('Post Weekday')['Total Interactions'].sum().idxmax()
x

4

In [74]:
# 8) Print the information of the posts where likes are above 200 and shares are above 30
x=df[(df['like']>200) & (df['share']>30)]
x

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
468,91651,Photo,1,2,4,12,0.0,15288,31467,1573,1401,2110,28247,13312,1052,5,264.0,36.0,305
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378

In [81]:
# 9) Which kind of posts are posted maximum number of times in November month
x = df[df['Post Month'] == 11]['Type'].value_counts().idxmax()
x

'Photo'

In [84]:
# 10) Find average and median of interactions for the paid (1) posts
x=df[(df['Paid']== 1)]['Total Interactions'].mean()
y=df[(df['Paid']== 1)]['Total Interactions'].median()
print(x)
print(y)

278.23021582733816
158.0